export const mappings: Array<[string, string]> = [
	["how are you doing", "how ya goin"],
	["how are you going", "how ya goin"],
	["how are you", "how ya goin"],
	["what are you doing", "whatcha up to"],
	["what is going on", "what's the go"],
	["what is happening", "what's the go"],
	["what do you think", "what reckon ya"],
	["thank you very much", "cheers heaps, legend"],
	["thank you so much", "cheers heaps, legend"],
	["thank you", "cheers, legend"],
	["thanks a lot", "cheers heaps"],
	["excuse me", "scuse me"],
	["see you later", "catch ya later, mate"],
	["see you soon", "catch ya soon, mate"],
	["talk to you later", "catch ya later"],
	["good morning", "g'day, legend"],
	["good afternoon", "g'day, legend"],
	["good evening", "g'day, legend"],
	["good day", "g'day"],
	["good on you", "good on ya"],
	["for your information", "just so ya know"],
	["i do not know", "dunno"],
	["i don't know", "dunno"],
	["do not worry", "no worries"],
	["don't worry", "no worries"],
	["no problem", "no worries"],
	["that is okay", "she'll be right"],
	["it will be okay", "she'll be right"],
	["everything will be okay", "she'll be right"],
	["a lot of", "heaps of"],
	["a lot", "heaps"],
	["very good", "bloody grouse"],
	["really good", "bloody grouse"],
	["very bad", "proper ordinary"],
	["really bad", "proper ordinary"],
	["very tired", "absolutely rooted"],
	["really tired", "absolutely rooted"],
	["very drunk", "absolutely munted"],
	["really drunk", "absolutely munted"],
	["very hungry", "proper peckish"],
	["really hungry", "proper peckish"],
	["very hot", "stinking hot"],
	["very cold", "bloody freezing"],
	["as soon as possible", "quick smart"],
	["right away", "quick smart"],
	["of course", "too right"],
	["for sure", "too right"],
	["all right", "no worries"],
	["all good", "no worries"],
	["by the way", "anyway"],
	["in the afternoon", "this arvo"],
	["this afternoon", "this arvo"],
	["a barbecue", "a barbie"],
	["barbecue", "barbie"],
	["fast food", "Macca's"],
	["gas station", "servo"],
	["petrol station", "servo"],
	["liquor store", "bottle-o"],
	["convenience store", "servo"],
	["swimming costume", "cossie"],
	["swimsuit", "cossie"],
	["flip flops", "thongs"],
	["flip-flops", "thongs"],
	["trash can", "rubbish bin"],
	["garbage can", "rubbish bin"],
	["takeout", "takeaway"],
	["take out", "takeaway"],
	["parking lot", "car park"],
	["parking space", "car park"],
	["cell phone", "mobile"],
	["mobile phone", "mobile"],
	["text message", "texta"],
	["sunglasses", "sunnies"],
	["breakfast", "brekkie"],
	["afternoon", "arvo"],
	["mosquito", "mozzie"],
	["chocolate", "choccy"],
	["sandwich", "sanga"],
	["biscuit", "bikkie"],
	["cookie", "bikkie"],
	["cigarette", "durry"],
	["firefighter", "firie"],
	["electrician", "sparky"],
	["tradesperson", "tradie"],
	["construction worker", "tradie"],
	["university", "uni"],
	["kindergarten", "kindy"],
	["football", "footy"],
	["soccer", "footy"],
	["friend", "mate"],
	["friends", "mates"],
	["man", "bloke"],
	["woman", "sheila"],
	["person", "legend"],
	["people", "legends"],
	["children", "ankle biters"],
	["child", "ankle biter"],
	["baby", "bub"],
	["father", "dad"],
	["mother", "mum"],
	["grandmother", "nan"],
	["grandfather", "pop"],
	["yes", "yeah"],
	["no", "nah"],
	["hello", "g'day"],
	["hi", "g'day"],
	["goodbye", "hoo roo, mate"],
	["awesome", "grouse"],
	["amazing", "bloody grouse"],
	["great", "grouse"],
	["excellent", "grouse"],
	["cool", "heaps good"],
	["nice", "beaut"],
	["perfect", "beaut"],
	["beautiful", "beaut"],
	["good", "beaut"],
	["bad", "ordinary"],
	["boring", "a bit ordinary"],
	["strange", "cooked"],
	["weird", "cooked"],
	["crazy", "cooked"],
	["angry", "ropeable"],
	["annoyed", "ropeable"],
	["upset", "spewin'"],
	["disappointed", "spewin'"],
	["embarrassed", "mortified"],
	["tired", "rooted"],
	["exhausted", "rooted"],
	["drunk", "munted"],
	["intoxicated", "munted"],
	["hungover", "seedy"],
	["sick", "crook"],
	["ill", "crook"],
	["injured", "crook"],
	["hungry", "peckish"],
	["thirsty", "parched"],
	["full", "chockers"],
	["busy", "flat out"],
	["cheap", "cheapie"],
	["expensive", "exxy"],
	["small", "tiny little"],
	["far away", "out woop woop"],
	["remote", "out woop woop"],
	["rural", "out bush"],
	["outside", "out bush"],
	["home", "back home"],
	["bathroom", "dunny"],
	["toilet", "dunny"],
	["bathroom break", "loo break"],
	["diaper", "nappy"],
	["sweater", "jumper"],
	["hoodie", "jumper"],
	["sweatpants", "trackies"],
	["sneakers", "runners"],
	["shoes", "runners"],
	["pickup truck", "ute"],
	["truck", "ute"],
	["vehicle", "car"],
	["car trunk", "boot"],
	["hood of the car", "bonnet"],
	["windshield", "windscreen"],
	["license plate", "rego"],
	["driver's license", "license"],
	["vacation", "holiday"],
	["vacationing", "on holiday"],
	["movie", "film"],
	["movies", "films"],
	["television", "telly"],
	["candy", "lollies"],
	["french fries", "hot chips"],
	["fries", "hot chips"],
	["chips", "hot chips"],
	["ketchup", "tomato sauce"],
	["tomato ketchup", "tomato sauce"],
	["dessert", "sweet"],
	["beer", "tinnie"],
	["beers", "tinnies"],
	["can of beer", "tinnie"],
	["wine", "goon"],
	["alcohol", "grog"],
	["drink", "bevvie"],
	["drinks", "bevvies"],
	["water", "the good stuff"],
	["coffee", "cuppa"],
	["tea", "cuppa"],
	["cup of tea", "cuppa"],
	["cup of coffee", "cuppa"],
	["store", "shop"],
	["shopkeeper", "shop bloke"],
	["boss", "big boss"],
	["police officer", "copper"],
	["police", "coppers"],
	["ambulance", "ambo"],
	["paramedic", "ambo"],
	["party", "piss-up"],
	["fight", "blue"],
	["argument", "blue"],
	["mistake", "stuff-up"],
	["problem", "stuff-up"],
	["mess", "dog's breakfast"],
	["nonsense", "rubbish"],
	["lie", "porky"],
	["idiot", "drongo"],
	["fool", "drongo"],
	["lazy person", "bludger"],
	["unreliable person", "dropkick"],
	["complain", "have a whinge"],
	["complaining", "having a whinge"],
	["leave", "nick off"],
	["go away", "rack off"],
	["go", "head off"],
	["going", "heading off"],
	["arrive", "rock up"],
	["arrived", "rocked up"],
	["wait", "hang on"],
	["look", "have a squiz"],
	["watch", "have a squiz"],
	["understand", "get it"],
	["understood", "got it"],
	["think", "reckon"],
	["believe", "reckon"],
	["want", "feel like"],
	["need", "have to"],
	["have to", "gotta"],
	["going to", "gonna"],
	["want to", "wanna"],
	["give me", "gimme"],
	["let me", "lemme"],
	["because", "'cause"],
	["about", "'bout"],
	["probably", "probs"],
	["definitely", "defo"],
	["absolutely", "bloody"],
	["extremely", "bloody"],
	["really", "proper"],
	["very", "bloody"],
	["completely", "fully"],
	["almost", "nearly"],
	["maybe", "reckon maybe"],
	["perhaps", "reckon maybe"],
	["again", "once more"],
	["now", "right now"],
	["later", "after"],
	["tomorrow", "tomoz"],
	["money", "dosh"],
	["dollars", "bucks"],
	["job", "gig"],
	["work", "graft"],
	["house", "place"],
	["apartment", "flat"],
	["roommate", "housemate"],
	["internet", "the internet"],
	["computer", "laptop"],
	["phone", "mobile"],
	["photo", "pic"],
	["picture", "pic"],
	["video", "vid"],
	["message", "yarn"],
	["conversation", "yarn"],
	["story", "yarn"],
	["information", "oil"],
	["gossip", "goss"],
	["announcement", "heads-up"],
	["warning", "heads-up"],
	["help", "give us a hand"],
	["please", "if ya reckon"],
	["sorry", "sorry mate"],
	["welcome", "no worries"],
	["okay", "righto"],
	["ok", "righto"],
	["sure", "too right"],
	["fine", "sweet as"],
	["ready", "good to go"],
	["done", "sorted"],
	["finished", "sorted"],
	["start", "kick off"],
	["stop", "pull up"],
	["hurry", "get a wriggle on"],
	["careful", "watch it"],
	["quiet", "quiet as"],
	["loud", "loud as"],
	["hot", "scorching"],
	["cold", "freezing"],
	["rain", "bucketing down"],
	["sunny", "stinking sunny"],
	["ocean", "the ocean"],
	["forest", "the bush"],
	["woods", "the bush"],
	["country", "the bush"],
	["insect", "bug"],
	["dog", "doggo"],
	["cat", "catto"],
	["bird", "birdo"],
	["food", "tucker"],
	["meal", "feed"],
	["lunch", "smoko"],
	["dinner", "tea"],
	["restaurant", "pub"],
	["bar", "pub"],
	["friendship", "mateship"],
	["happiness", "good vibes"],
	["success", "a win"],
	["failure", "a shocker"],
	["easy", "easy as"],
	["difficult", "a bit cooked"],
	["hard", "a bit cooked"],
	["fast", "quick smart"],
	["slow", "taking yonks"],
	["early", "bright and early"],
	["late", "running late"],
	["enough", "heaps"],
	["many", "heaps of"],
	["much", "heaps of"],
	["everyone", "every legend"],
	["somebody", "some legend"],
	["someone", "some legend"],
	["nothing", "bugger all"],
	["something", "a thingo"],
	["things", "bits and pieces"],
	["stuff", "bits and pieces"],
	["thing", "thingo"],
	["why", "how come"],
	["and", "'n"],
	["an", "a"],
	["my", "me"],
	["your", "ya"],
	["you", "ya"],
	["you are", "ya're"],
	["yourself", "yaself"],
	["because of", "'cause of"],
	["cannot", "can't"],
	["do not", "don't"],
	["does not", "doesn't"],
	["is not", "isn't"],
	["are not", "aren't"],
	["will not", "won't"],
	["should not", "shouldn't"],
	["would not", "wouldn't"],
	["could not", "couldn't"],
	["i am", "I'm"],
	["i have", "I've"],
	["i will", "I'll"],
	["we are", "we're"],
	["they are", "they're"],
	["it is", "it's"],
	["that is", "that's"],
	["there is", "there's"],
	["academic", "acca"],
	["academics", "accas"],
	["business", "bizzo"],
	["journalist", "journo"],
	["journalists", "journos"],
	["documentary", "doco"],
	["documentaries", "docos"],
	["vegetarian", "vego"],
	["vegetarians", "vegos"],
	["devastated", "devo"],
	["compensation", "compo"],
	["garbage collector", "garbo"],
	["garbage collectors", "garbos"],
	["lipstick", "lippie"],
	["tasmania", "Tassie"],
	["relative", "rellie"],
	["relatives", "rellies"],
	["tracksuit pants", "trackie daks"],
	["tracksuit bottoms", "trackie daks"],
	["turn left", "chuck a left"],
	["turn right", "chuck a right"],
	["make a u-turn", "chuck a u-ey"],
	["u-turn", "u-ey"],
	["kilometre", "click"],
	["kilometres", "clicks"],
	["kilometer", "click"],
	["kilometers", "clicks"],
	["car accident", "prang"],
	["car accidents", "prangs"],
	["traffic accident", "prang"],
	["traffic accidents", "prangs"],
	["minor accident", "bingle"],
	["minor accidents", "bingles"],
	["car crash", "prang"],
	["car crashes", "prangs"],
	["little children", "little tackers"],
	["young children", "little tackers"],
	["look around", "have a stickybeak"],
	["have a look", "have a captain cook"],
	["take a look", "have a captain cook"],
	["back off", "pull your head in"],
	["mind your own business", "pull your head in"],
	["take a day off", "chuck a sickie"],
	["take sick leave", "chuck a sickie"],
	["sick leave", "sickie"],
	["smoking break", "smoko"],
	["coffee break", "smoko"],
	["work break", "smoko"],
	["firefighters", "firies"],
	["politician", "pollie"],
	["politicians", "pollies"],
	["environmentalist", "greenie"],
	["environmentalists", "greenies"],
	["holiday", "hollie"],
	["holidays", "hollies"],
	["bottle shop", "bottle-o"],
	["bottle shops", "bottle-os"],
	["liquor shop", "bottle-o"],
	["liquor shops", "bottle-os"],
	["milkman", "milko"],
	["milk delivery person", "milko"],
	["swimming briefs", "budgie smugglers"],
	["swim briefs", "budgie smugglers"],
	["swimming trunks", "budgie smugglers"],
	["cooler", "esky"],
	["coolers", "eskies"],
	["ice chest", "esky"],
	["cool box", "esky"],
	["short trousers", "stubbies"],
	["beer bottle", "stubby"],
	["beer bottles", "stubbies"],
	["can cooler", "stubby holder"],
	["can coolers", "stubby holders"],
	["chicken", "chook"],
	["chickens", "chooks"],
	["kangaroo", "roo"],
	["kangaroos", "roos"],
	["crocodile", "croc"],
	["crocodiles", "crocs"],
	["fly", "blowie"],
	["flies", "blowies"],
	["outback", "the bush"],
	["rural area", "the bush"],
	["remote area", "woop woop"],
	["old car", "bomb"],
	["unreliable car", "bomb"],
	["reckless driver", "hoon"],
	["reckless drivers", "hoons"],
	["driving recklessly", "hooning"],
	["police officers", "coppers"],
	["jail", "the slammer"],
	["prison", "the slammer"],
	["arrest", "nick"],
	["arrested", "nicked"],
	["tell on", "dob on"],
	["report someone", "dob in"],
	["informer", "dobber"],
	["informers", "dobbers"],
	["try it", "give it a burl"],
	["give it a try", "give it a burl"],
	["have a try", "have a crack"],
	["give it a chance", "give it a crack"],
	["farmer", "cocky"],
	["farmers", "cockies"],
	["hardworking person", "battler"],
	["hardworking people", "battlers"],
	["uncultured person", "bogan"],
	["uncultured people", "bogans"],
	["unfashionable person", "dag"],
	["unfashionable people", "dags"],
	["unintelligent person", "galah"],
	["unintelligent people", "galahs"],
	["sausage", "snag"],
	["sausages", "snags"],
	["sandwiches", "sangas"],
	["chicken parmesan", "chicken parma"],
	["chicken parmigiana", "chicken parma"],
	["ice pop", "icy pole"],
	["ice pops", "icy poles"],
	["popsicle", "icy pole"],
	["popsicles", "icy poles"],
	["boxed wine", "goon"],
	["wine cask", "goon"],
	["canned beer", "tinnie"],
	["canned beers", "tinnies"],
	["grocery store", "the shops"],
	["grocery stores", "the shops"],
	["go shopping", "hit the shops"],
	["go to the shops", "hit the shops"],
	["shopping trip", "shopping run"],
	["movie theatre", "cinema"],
	["movie theaters", "cinemas"],
	["music concert", "gig"],
	["music concerts", "gigs"],
	["newspaper", "rag"],
	["newspapers", "rags"],
	["magazine", "mag"],
	["magazines", "mags"],
	["front porch", "verandah"],
	["porch", "verandah"],
	["porches", "verandahs"],
	["garbage", "rubbish"],
	["trash", "rubbish"],
	["trash bag", "rubbish bag"],
	["trash bags", "rubbish bags"],
	["water fountain", "bubbler"],
	["water fountains", "bubblers"],
	["bathing suit", "cossie"],
	["swimsuits", "cossies"],
	["toilets", "dunnies"],
	["sunburned", "sunburnt"],
	["nervous", "on edge"],
	["aggressive", "aggro"],
	["angry person", "a grumpy bugger"],
	["very angry", "ropeable"],
	["heavy rain", "bucketing down"],
	["raining heavily", "bucketing down"],
	["very hot day", "a scorcher"],
	["hot day", "a scorcher"],
	["everything is fine", "she'll be right, mate"],
	["everything is okay", "she'll be right, mate"],
	["all is well", "she'll be right, mate"],
	["very genuine", "true blue"],
	["very loyal", "true blue"],
	["australian", "Aussie"],
	["australians", "Aussies"],
	["good job", "bloody good on ya"],
	["well done", "bloody good on ya"],
	["great idea", "a bloody ripper idea"],
	["bad idea", "a cooked idea"],
	["this is great", "this is bloody grouse"],
	["that is great", "that is bloody grouse"],
	["this is amazing", "this is an absolute ripper"],
	["that is amazing", "that is an absolute ripper"],
	["this is terrible", "this is an absolute shocker"],
	["that is terrible", "that is an absolute shocker"],
	["this is strange", "this is cooked as"],
	["that is strange", "that is cooked as"],
	["this is weird", "this is cooked as"],
	["that is weird", "that is cooked as"],
	["this is annoying", "this is doing my head in"],
	["that is annoying", "that is doing my head in"],
	["you are annoying", "you're doing my head in"],
	["you are joking", "you're having a laugh"],
	["you are kidding", "you're having a laugh"],
	["i am joking", "I'm having a laugh"],
	["i am kidding", "I'm having a laugh"],
	["i am tired", "I'm absolutely rooted"],
	["i am exhausted", "I'm absolutely rooted"],
	["i am hungry", "I'm bloody peckish"],
	["i am thirsty", "I'm dry as"],
	["i am busy", "I'm flat out"],
	["i am late", "I'm running late"],
	["i am broke", "I'm skint"],
	["i have no money", "I'm skint"],
	["i am drunk", "I'm absolutely munted"],
	["i am hungover", "I'm seedy as"],
	["i am sick", "I'm crook"],
	["i am not feeling well", "I'm feeling crook"],
	["i am embarrassed", "I'm devo"],
	["i am annoyed", "I'm ropeable"],
	["i have no idea", "no bloody clue"],
	["i do not understand", "I don't get it, mate"],
	["i am confused", "I don't know if I'm Arthur or Martha"],
	["i cannot believe it", "I can't believe it, mate"],
	["i agree", "too right"],
	["i disagree", "yeah, nah"],
	["i do not agree", "yeah, nah"],
	["what happened", "what's the go"],
	["what is this", "what's this then"],
	["what is wrong", "what's the go"],
	["are you serious", "are ya fair dinkum"],
	["seriously", "fair dinkum"],
	["no way", "get stuffed"],
	["come on", "c'mon, mate"],
	["hurry up", "rattle your dags"],
	["wait a minute", "hang on a tick"],
	["wait a second", "hang on a sec"],
	["give me a second", "give us a tick"],
	["give me a minute", "give us a tick"],
	["i am leaving", "I'm off"],
	["i am going home", "I'm heading home"],
	["i am coming", "I'm on me way"],
	["let us go", "let's get a wriggle on"],
	["i will do it", "I'll sort it"],
	["i will fix it", "I'll sort it"],
	["you can do it", "you've got this, mate"],
	["can you help me", "can ya give us a hand"],
	["i need help", "I need a hand, mate"],
	["stop complaining", "stop having a whinge"],
	["do not complain", "don't have a whinge"],
	["stop talking", "give it a rest"],
	["be quiet", "give it a rest"],
	["leave me alone", "rack off"],
	["be careful", "watch yourself"],
	["i love it", "I bloody love it"],
	["i hate it", "I bloody hate it"],
	["it is easy", "easy as"],
	["it is difficult", "a bit cooked"],
	["that is expensive", "that's exxy as"],
	["this is expensive", "this is exxy as"],
	["that is cheap", "that's cheap as chips"],
	["this is cheap", "this is cheap as chips"],
	["you are welcome", "no worries, mate"],
	["very impressive", "the ant's pants"],
	["extremely impressive", "the ant's pants"],
	["the best", "the ant's pants"],
	["boast", "big-note"],
	["boasting", "big-noting"],
	["boastful person", "big noter"],
	["boastful people", "big noters"],
	["fake", "bodgie"],
	["false", "bodgie"],
	["worthless", "bodgie"],
	["wild horse", "brumby"],
	["wild horses", "brumbies"],
	["socially awkward person", "dag"],
	["socially awkward people", "dags"],
	["get moving", "rattle your dags"],
	["be genuine", "be dinkum"],
	["be honest", "be dinkum"],
	["reliable", "dinkum"],
	["honest", "dinkum"],
	["very full", "full as a goog"],
	["completely full", "full as a goog"],
	["news", "oil"],
	["inside information", "the oil"],
	["lose your temper", "chuck a wobbly"],
	["lose my temper", "chuck a wobbly"],
	["lose their temper", "chuck a wobbly"],
	["have a tantrum", "chuck a wobbly"],
	["throw a tantrum", "chuck a wobbly"],
	["give up in anger", "spit the dummy"],
	["stop participating in anger", "spit the dummy"],
	["swim", "have a bogey"],
	["go swimming", "have a bogey"],
	["go for a swim", "have a bogey"],
	["take a bath", "have a bogey"],
	["bathe", "bogey"],
	["portable cooler", "esky"],
	["insulated cooler", "esky"],
	["motorcycle gang member", "bikie"],
	["motorcycle gang members", "bikies"],
	["uncultured australian man", "ocker"],
	["uncultured australian men", "ockers"],
	["red-haired person", "bluey"],
	["red-haired people", "blueys"],
	["person with red hair", "bluey"],
	["person who is very australian", "true blue Aussie"],
	["person who is very loyal", "true blue Aussie"],
	["show off", "lair up"],
	["showing off", "lairing up"],
	["show-off", "lair"],
	["show-offs", "lairs"],
	["flashily dressed person", "lair"],
	["flashily dressed people", "lairs"],
	["mischievous person", "larrikin"],
	["mischievous people", "larrikins"],
	["good-hearted rogue", "larrikin"],
	["good-hearted rogues", "larrikins"],
	["joker", "larrikin"],
	["jokers", "larrikins"],
	["buy on instalments", "lay-by"],
	["buy on installments", "lay-by"],
	["pay in instalments", "lay-by"],
	["pay in installments", "lay-by"],
	["extremely busy", "flat out like a lizard drinking"],
	["very busy", "flat out like a lizard drinking"],
	["search", "fossick"],
	["searching", "fossicking"],
	["rummage", "fossick"],
	["rummaging", "fossicking"],
	["very happy", "happy as Larry"],
	["extremely happy", "happy as Larry"],
	["cheerful person", "happy little Vegemite"],
	["cheerful people", "happy little Vegemites"],
	["lonely", "like a shag on a rock"],
	["isolated", "like a shag on a rock"],
	["criticize", "sledge"],
	["criticise", "sledge"],
	["mock", "sledge"],
	["make fun of", "sledge"],
	["accept bad luck", "such is life"],
	["accept the situation", "such is life"],
	["life is hard", "life wasn't meant to be easy"],
	["valuable person", "blood's worth bottling"],
	["valuable people", "blood's worth bottling"],
	["loyal friend", "blood's worth bottling"],
	["loyal friends", "blood's worth bottling"],
	["win narrowly", "blouse"],
	["won narrowly", "bloused"],
	["defeat narrowly", "blouse"],
	["defeated narrowly", "bloused"],
	["knowledgeable person", "full bottle"],
	["knowledgeable people", "full bottles"],
	["expert", "full bottle"],
	["experts", "full bottles"],
	["badly informed", "not the full bottle"],
	["unfair deal", "raw prawn"],
	["unfair action", "raw prawn"],
	["try to deceive", "come the raw prawn"],
	["try to fool", "come the raw prawn"],
	["fools", "boofheads"],
	["dimwitted person", "boofhead"],
	["dimwitted people", "boofheads"],
	["very crazy", "mad as a cut snake"],
	["extremely crazy", "mad as a cut snake"],
	["very fit", "fit as a Mallee bull"],
	["extremely fit", "fit as a Mallee bull"],
	["bedroll", "swag"],
	["bedrolls", "swags"],
	["traveller's bedroll", "matilda"],
	["traveller's bedrolls", "matildas"],
	["idle person", "bludger"],
	["idle people", "bludgers"],
	["freeloader", "bludger"],
	["freeloaders", "bludgers"],
	["cadger", "bludger"],
	["cadgers", "bludgers"],
	["non-contributor", "bludger"],
	["non-contributors", "bludgers"],
	["gold miner", "digger"],
	["gold miners", "diggers"],
	["australian soldier", "digger"],
	["australian soldiers", "diggers"],
	["blue blanket bedroll", "bluey"],
	["blue blanket bedrolls", "blueys"],
	["splendid", "bonzer"],
	["superb", "bonzer"],
	["terrific", "bonzer"],
	["fantastic", "bonzer"],
	["outstanding", "bonzer"],
	["exceptional", "bonzer"],
	["marvellous", "bonzer"],
	["marvelous", "bonzer"],
	["excellent thing", "bonzer"],
	["excellent things", "bonzers"],
	["shoddy", "bodgie"],
	["counterfeit", "bodgie"],
	["bogus", "bodgie"],
	["fraudulent", "bodgie"],
	["low-quality", "bodgie"],
	["low quality", "bodgie"],
	["fake item", "bodgie"],
	["fake items", "bodgies"],
	["counterfeit item", "bodgie"],
	["counterfeit items", "bodgies"],
	["knowledgeable", "full bottle"],
	["well informed", "full bottle"],
	["well-informed", "full bottle"],
	["well versed", "full bottle"],
	["well-versed", "full bottle"],
	["not knowledgeable", "not the full bottle"],
	["not well informed", "not the full bottle"],
	["not well-informed", "not the full bottle"],
	["deception", "raw prawn"],
	["deceptive act", "raw prawn"],
	["misrepresentation", "raw prawn"],
	["try to trick", "come the raw prawn"],
	["try to con", "come the raw prawn"],
	["treat me like a fool", "come the raw prawn"],
	["treat someone like a fool", "come the raw prawn"],
	["i am not stupid", "I didn't come down in the last shower"],
	["i was not born yesterday", "I didn't come down in the last shower"],
	["do not try to fool me", "don't come the raw prawn with me"],
	["insane", "mad as a cut snake"],
	["mad", "mad as a cut snake"],
	["eccentric", "mad as a cut snake"],
	["furious", "mad as a cut snake"],
	["enraged", "mad as a cut snake"],
	["extremely angry", "mad as a cut snake"],
	["completely crazy", "mad as a cut snake"],
	["wildly angry", "mad as a cut snake"],
	["wildly crazy", "mad as a cut snake"],
	["small blanket roll", "swag"],
	["small blanket rolls", "swags"],
	["travelling bedroll", "swag"],
	["travelling bedrolls", "swags"],
	["hiker's bedroll", "swag"],
	["hiker's bedrolls", "swags"],
	["traveller's belongings", "swag"],
	["traveller's blanket roll", "matilda"],
	["mischievous youth", "larrikin"],
	["mischievous youths", "larrikins"],
	["good-hearted troublemaker", "larrikin"],
	["good-hearted troublemakers", "larrikins"],
	["carefree rebel", "larrikin"],
	["carefree rebels", "larrikins"],
	["prankster", "larrikin"],
	["pranksters", "larrikins"],
	["look for", "fossick for"],
	["look around for", "fossick for"],
	["hunt for", "fossick for"],
	["hunt around", "fossick around"],
	["rummage around", "fossick around"],
	["search around", "fossick around"],
	["search through", "fossick through"],
	["look through", "fossick through"],
	["very occupied", "flat out like a lizard drinking"],
	["completely occupied", "flat out like a lizard drinking"],
	["working very hard", "flat out like a lizard drinking"],
	["working at top speed", "flat out like a lizard drinking"],
	["incredibly busy", "flat out like a lizard drinking"],
	["absolutely busy", "flat out like a lizard drinking"],
	["busy all day", "flat out like a lizard drinking"],
	["busy at work", "flat out like a lizard drinking"],
	["long chat", "galah session"],
	["long conversation", "galah session"],
	["chat for a long time", "have a galah session"],
	["gossip session", "galah session"],
	["liven things up", "stir the possum"],
	["start a controversy", "stir the possum"],
	["create controversy", "stir the possum"],
	["generate discussion", "stir the possum"],
	["stupid person", "prawn"],
	["stupid people", "prawns"],
	["very stupid", "a stubby short of a sixpack"],
	["extremely stupid", "a stubby short of a sixpack"],
	["not very smart", "a stubby short of a sixpack"],
	["defeated completely", "done like a dinner"],
	["beaten completely", "done like a dinner"],
	["comprehensively defeated", "done like a dinner"],
	["comprehensively beaten", "done like a dinner"],
	["very remote place", "beyond the black stump"],
	["very remote places", "beyond the black stump"],
	["far beyond civilisation", "beyond the black stump"],
	["far beyond civilization", "beyond the black stump"],
	["deep in the outback", "beyond the black stump"],
	["very obvious", "blind Freddy could see it"],
	["completely obvious", "blind Freddy could see it"],
	["easy to see", "blind Freddy could see it"],
	["easy to understand", "blind Freddy could see it"],
	["reasonable chance", "fair go"],
	["fair chance", "fair go"],
	["fair deal", "fair go"],
	["be reasonable", "fair suck of the sauce bottle"],
	["that is unfair", "fair suck of the sauce bottle"],
	["this is unfair", "fair suck of the sauce bottle"],
	["unfair outcome", "the rough end of the pineapple"],
	["unfair outcomes", "the rough end of the pineapple"],
	["bad deal", "the rough end of the pineapple"],
	["bad deals", "the rough end of the pineapple"],
	["retire and return", "do a Melba"],
	["return after retirement", "do a Melba"],
	["make a comeback after retiring", "do a Melba"],
	["repeated comeback", "do a Melba"],
	["large sum of money", "motza"],
	["large sums of money", "motzas"],
	["huge amount of money", "motza"],
	["huge amounts of money", "motzas"],
	["fortune", "motza"],
	["windfall", "motza"],
	["jinx someone", "put the mozz on"],
	["bring bad luck", "put the mozz on"],
	["put a curse on", "put the mozz on"],
	["dazed", "like a stunned mullet"],
	["stupefied", "like a stunned mullet"],
	["uncomprehending", "like a stunned mullet"],
	["shocked", "like a stunned mullet"],
	["great gift", "straight to the poolroom"],
	["great gifts", "straight to the poolroom"],
	["valuable gift", "straight to the poolroom"],
	["valuable gifts", "straight to the poolroom"],
	["great prize", "straight to the poolroom"],
	["great prizes", "straight to the poolroom"],
	["not my first time", "I didn't come down in the last shower"],
	["i know better", "I didn't come down in the last shower"],
	["do not treat me as foolish", "don't come the raw prawn with me"],
	["overconfident person", "someone with tickets on themselves"],
	["overconfident people", "people with tickets on themselves"],
	["person who refuses to work", "someone who wouldn't work in an iron lung"],
	["people who refuse to work", "people who wouldn't work in an iron lung"],
];

export const australianSpellings: Record<string, string> = {
	"aging": "ageing",
	"analog": "analogue",
	"analyze": "analyse",
	"analyzed": "analysed",
	"analyzes": "analyses",
	"analyzing": "analysing",
	"armor": "armour",
	"behavior": "behaviour",
	"behaviors": "behaviours",
	"canceled": "cancelled",
	"canceling": "cancelling",
	"catalog": "catalogue",
	"categorize": "categorise",
	"center": "centre",
	"centers": "centres",
	"check": "cheque",
	"checks": "cheques",
	"color": "colour",
	"colors": "colours",
	"colorful": "colourful",
	"coloring": "colouring",
	"customize": "customise",
	"customized": "customised",
	"customizes": "customises",
	"customizing": "customising",
	"defense": "defence",
	"defenses": "defences",
	"dialog": "dialogue",
	"dialogs": "dialogues",
	"discolor": "discolour",
	"dishonor": "dishonour",
	"dishonored": "dishonoured",
	"dishonors": "dishonours",
	"dramatize": "dramatise",
	"favorite": "favourite",
	"favorites": "favourites",
	"favor": "favour",
	"favored": "favoured",
	"favors": "favours",
	"favoring": "favouring",
	"fiber": "fibre",
	"fibers": "fibres",
	"fulfill": "fulfil",
	"fulfilled": "fulfilled",
	"fulfilling": "fulfilling",
	"gray": "grey",
	"harbor": "harbour",
	"harbors": "harbours",
	"honor": "honour",
	"honored": "honoured",
	"honors": "honours",
	"humor": "humour",
	"humors": "humours",
	"idealize": "idealise",
	"installment": "instalment",
	"jewelry": "jewellery",
	"judgment": "judgement",
	"labor": "labour",
	"labored": "laboured",
	"laboring": "labouring",
	"localize": "localise",
	"maximization": "maximisation",
	"maximize": "maximise",
	"maximized": "maximised",
	"maximizes": "maximises",
	"maximizing": "maximising",
	"meter": "metre",
	"meters": "metres",
	"modeling": "modelling",
	"modeler": "modeller",
	"modelers": "modellers",
	"mold": "mould",
	"molds": "moulds",
	"mom": "mum",
	"moms": "mums",
	"mustache": "moustache",
	"neighbor": "neighbour",
	"neighbors": "neighbours",
	"normalize": "normalise",
	"optimized": "optimised",
	"optimize": "optimise",
	"optimizes": "optimises",
	"optimizing": "optimising",
	"organization": "organisation",
	"organizations": "organisations",
	"organize": "organise",
	"organized": "organised",
	"organizes": "organises",
	"organizing": "organising",
	"paralyze": "paralyse",
	"penalize": "penalise",
	"practice": "practice",
	"program": "programme",
	"programs": "programmes",
	"realize": "realise",
	"realized": "realised",
	"realizes": "realises",
	"realizing": "realising",
	"recognize": "recognise",
	"recognized": "recognised",
	"recognizes": "recognises",
	"recognizing": "recognising",
	"savior": "saviour",
	"specialize": "specialise",
	"specialized": "specialised",
	"specializes": "specialises",
	"specializing": "specialising",
	"sulfur": "sulphur",
	"theater": "theatre",
	"theaters": "theatres",
	"traveling": "travelling",
	"traveled": "travelled",
	"traveler": "traveller",
	"travelers": "travellers",
	"utilize": "utilise",
	"utilized": "utilised",
	"utilizes": "utilises",
	"utilizing": "utilising",
	"vapor": "vapour",
	"vapors": "vapours",
	"visualize": "visualise",
	"visualized": "visualised",
	"visualizes": "visualises",
	"visualizing": "visualising",
};
