import { readFileSync } from 'fs';
import { resolve } from 'path';
import { fileURLToPath } from 'url';
import json from '@rollup/plugin-json';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import iife from 'rollup-plugin-iife';
import { swc } from 'rollup-plugin-swc3';
const root=fileURLToPath(new URL('.',import.meta.url));
const wrapper={name:'wrapper',generateBundle(_,bundle){for(const chunk of Object.values(bundle)){if(chunk.type!=='chunk')continue;let code=chunk.code.trim().replace(/^var\s+[A-Za-z_$][\w$]*\s*=\s*/,'').replace(/;\s*$/,'');chunk.code=`({__plugin:null,__load(){if(this.__plugin)return this.__plugin;this.__plugin=${code};return this.__plugin},start(){return this.__load()?.start?.()},stop(){return this.__load()?.stop?.()}})`}}};
const manifest={name:'manifest',buildStart(){const data=JSON.parse(readFileSync(resolve(root,'manifest.json'),'utf8'));data.main='index.js';this.emitFile({type:'asset',fileName:'manifest.json',source:`${JSON.stringify(data,null,'\t')}\n`})}};
export default {input:'src/index.tsx',external:['@unbound-app/api','react','react-native'],plugins:[nodeResolve(),json(),swc({tsconfig:false}),iife(),wrapper,manifest],output:{dir:'dist',entryFileNames:'index.js',format:'es',compact:true,globals:{'@unbound-app/api':'window.unbound',react:'window.React','react-native':'window.ReactNative'}}};
